### ISSUE TITLE
Add sources

### ISSUE THREAD

**Issue by xzfc** [ad-si/nix-companies#10]
It would be useful to have a source link for each entry confirming that a particular company uses nix. Similar to [haskell-companies](https://github.com/erkmos/haskell-companies) and [purescript-companies](https://github.com/ajnsit/purescript-companies).

And probably a short comment to make it clear to which extent it is used (e.g. being a "nix software consultancy" is not the same as using nix somewhere in the CI pipeline for a few projects).

**Comment by RobbieBuxton** [comment]
I think this is a good idea!

**Comment by ad-si** [comment]
Yeah, sources would be good! However, I don't like to put it right in the main table. Since this is a curated list, you would assume we did the due diligence when adding a new entry. So it's just taking up space with no value for the normal reader.
So maybe let's add another `sources.md` file where we list them? Then we also have more space for details and longer descriptions.

**Comment by RobbieBuxton** [comment]
> Yeah, sources would be good! However, I don't like to put it right in the main table. Since this is a curated list, you would assume we did the due diligence when adding a new entry. So it's just taking up space with no value for the normal reader.
> So maybe let's add another `sources.md` file where we list them? Then we also have more space for details and longer descriptions.

How about providing a citation with the name that links to the source in a similar style to how Wikipedia does it? E.g Amazon[1].

**Comment by ad-si** [comment]
Mh, or maybe a column like this (hover the ℹ️ to see the details):

name | ℹ️
-----|---
Corp | <span title="Blog post: https://corp.com/why-we-use-nix">ℹ️</span>

**Comment by RobbieBuxton** [comment]
> Mh, or maybe a column like this (hover the ℹ️ to see the details):
> 
> name | ℹ️
> -----|---
> Corp | <span title="Blog post: https://corp.com/why-we-use-nix">ℹ️</span>

Yeah, I like that better actually!

**Comment by ad-si** [comment]
I decided to go with a [`references.md`](https://github.com/ad-si/nix-companies/blob/main/references.md) file.
Maybe not the most elegant solution, but at least it is straight forward =D.
