### ISSUE TITLE
Add Cachix and Smallbrooks

### ISSUE THREAD

**Issue by xzfc** [ad-si/nix-companies#11]
Source: listed in [elm-companies](https://github.com/jah2488/elm-companies). Copied from their readme:

* [Cachix](https://cachix.org/) ([GitHub](https://github.com/cachix/elm2nix)) - Build Nix packages once and share them for good.

* [Smallbrooks](https://www.smallbrooks.com) - Copenhagen Denmark - Smallbrooks sell Saas crowdfunding platforms. Most of our user clients are written in Elm and we have 150.000+ lines of Elm code in production.  We have fun, so come work for us. We are fans of functional programming and use Scala on the backend and NixOS as dev environment.

**Comment by ad-si** [comment]
Sounds good! Would you be up for creating a PR for it? 🙂
