### ISSUE TITLE
Possible Company D. E. Shaw

### ISSUE THREAD

**Issue by RobbieBuxton** [ad-si/nix-companies#7]
The [Flox](https://flox.dev/about) origin, and this [Nix Discourse](https://discourse.nixos.org/t/the-d-e-shaw-group-quant-systems-build-and-release-engineer/13686) post seems to imply D. E. Shaw uses nix.

**Comment by PedroRegisPOAR** [comment]
Searched about the job in https://discourse.nixos.org/t/the-d-e-shaw-group-quant-systems-build-and-release-engineer/13686 in the [Wayback Machine](https://archive.org/web/) and found it (the original link is offline):


https://web.archive.org/web/20220112092835/https://www.deshaw.com/careers/quant-systems-build-and-release-engineer-new-york-4225

**Comment by ad-si** [comment]
Thanks! Added it in b44f7db.
